"""
Skull/brain alignment math — 3-point rotation + non-uniform scale.

Pure geometry, no picking / printing / file dialogs. Ported from
``objective_functionnality/skull_addapt.py`` so the GUI and any future
CLI can share one implementation. The transform dict produced by
:func:`compute_transform` uses the same schema as the original script's
``align_config.json`` / ``brain_to_skull_transform.json``, so configs
generated by either tool are interchangeable.
"""

from __future__ import annotations

from dataclasses import dataclass, fields
from typing import Optional

import numpy as np
import trimesh

CAVITY_SCALE_DEFAULT = 0.55

# Index, among the landmark-derived local axes (e1, e2, e3 -- see
# `make_frame`: antero-posterior, dorso-ventral, medio-lateral, in that
# order), of the medio-lateral axis. Bregma, Lambda and Ventral are all
# midline points, so both meshes have ~zero landmark separation along
# this one direction no matter how good the picks are -- it can never be
# derived from the landmarks the way the antero-posterior and
# dorso-ventral directions can. See `compute_transform`.
#
# NOTE: this indexes the LOCAL (e1, e2, e3) basis, not the mesh's own
# raw/native STL coordinate axes -- those can be in any arbitrary
# orientation depending on how the file was modeled, so scaling "raw axis
# 1" would only be medio-lateral by coincidence.
MEDIOLATERAL_AXIS = 2


def bbox_dims(mesh: trimesh.Trimesh) -> np.ndarray:
    return mesh.bounds[1] - mesh.bounds[0]


def bbox_center(mesh: trimesh.Trimesh) -> np.ndarray:
    return mesh.bounds.mean(axis=0)


def extent_along(mesh: trimesh.Trimesh, direction: np.ndarray) -> float:
    """Extent (max - min) of `mesh`'s vertices projected onto `direction`
    (need not be pre-normalized)."""
    d = direction / np.linalg.norm(direction)
    proj = mesh.vertices @ d
    return float(proj.max() - proj.min())


def make_frame(bregma: np.ndarray, lambda_: np.ndarray, ventral: np.ndarray) -> np.ndarray:
    e1 = lambda_ - bregma
    e1 = e1 / np.linalg.norm(e1)
    v = ventral - bregma
    e3 = np.cross(e1, v)
    if np.linalg.norm(e3) < 1e-6:
        raise ValueError(
            "The 3 landmarks are collinear — the ventral point lies on "
            "the Bregma-Lambda line."
        )
    e3 = e3 / np.linalg.norm(e3)
    e2 = np.cross(e3, e1)
    return np.column_stack([e1, e2, e3])


def frame_to_rotation_4x4(F_src: np.ndarray, F_dst: np.ndarray, origin_src: np.ndarray) -> np.ndarray:
    R3 = F_dst @ F_src.T
    M = np.eye(4)
    M[:3, :3] = R3
    M[:3, 3] = origin_src - R3 @ origin_src
    return M


def xform_pt(pt: Optional[np.ndarray], M: np.ndarray) -> Optional[np.ndarray]:
    if pt is None:
        return None
    return (M @ np.append(pt, 1.0))[:3]


def canonical_frame_transform(bregma: np.ndarray, lambda_: np.ndarray, ventral: np.ndarray) -> np.ndarray:
    """Rigid (rotation + translation, NO scale) transform that places::

        bregma -> (0, 0, 0)
        lambda -> (D, 0, 0)      D = |lambda - bregma|  (bregma-lambda distance)

    i.e. X is the antero-posterior (bregma->lambda) axis, Z is
    dorso-ventral, Y is medio-lateral. ``ventral`` only resolves the
    remaining spin around the bregma-lambda axis, via the same 3-point
    frame convention as :func:`make_frame`.
    """
    F_src = make_frame(bregma, lambda_, ventral)
    F_dst = np.column_stack([
        np.array([1.0, 0.0, 0.0]),   # bregma->lambda direction -> +X (antero-posterior)
        np.array([0.0, 0.0, 1.0]),   # +Z (dorso-ventral)
        np.array([0.0, -1.0, 0.0]),  # -Y (medio-lateral)
    ])
    R3 = F_dst @ F_src.T
    M = np.eye(4)
    M[:3, :3] = R3
    M[:3, 3] = -R3 @ bregma
    return M


@dataclass
class Landmarks:
    """The 3 paired landmarks used for alignment (Bregma, Lambda, Ventral)."""

    bregma_skull: Optional[np.ndarray] = None
    lambda_skull: Optional[np.ndarray] = None
    ventral_skull: Optional[np.ndarray] = None
    bregma_brain: Optional[np.ndarray] = None
    lambda_brain: Optional[np.ndarray] = None
    ventral_brain: Optional[np.ndarray] = None

    def have_3pts(self) -> bool:
        return all(getattr(self, f.name) is not None for f in fields(self))

    def have_2pts(self) -> bool:
        return all(
            getattr(self, name) is not None
            for name in ("bregma_skull", "lambda_skull", "bregma_brain", "lambda_brain")
        )

    def as_json(self) -> dict:
        return {
            f.name: (getattr(self, f.name).tolist() if getattr(self, f.name) is not None else None)
            for f in fields(self)
        }


def compute_transform(
    skull: trimesh.Trimesh,
    brain: trimesh.Trimesh,
    landmarks: Landmarks,
    *,
    skull_path: str,
    brain_path: str,
    cavity_scale: float = CAVITY_SCALE_DEFAULT,
) -> dict:
    """Compute the 4x4 transform that maps ``brain`` into ``skull`` space.

    Uses the 3-point landmark frame when all 6 points are available,
    falling back to a 2-point rotation (spin around the B-L axis left
    unconstrained) or no rotation at all, exactly like the original CLI
    script.

    Non-uniform scale is derived per landmark-local axis (antero-posterior,
    dorso-ventral, medio-lateral -- see `make_frame`) from the landmark
    distances (Bregma-Lambda, Bregma-Ventral), except the medio-lateral
    axis (:data:`MEDIOLATERAL_AXIS`), which those landmarks can't
    constrain since they're all midline points -- that axis is always
    driven by ``cavity_scale`` times the skull/brain extent ratio along
    that same landmark-derived direction instead. Working in this local
    basis (rather than the mesh's raw STL axes) makes the result
    independent of how either file happens to be oriented.
    """
    lm = landmarks
    have_3pts = lm.have_3pts()
    have_2pts = lm.have_2pts()

    F_skull = None
    if have_3pts:
        try:
            F_brain = make_frame(lm.bregma_brain, lm.lambda_brain, lm.ventral_brain)
            F_skull = make_frame(lm.bregma_skull, lm.lambda_skull, lm.ventral_skull)
            R4 = frame_to_rotation_4x4(F_brain, F_skull, lm.bregma_brain)
        except ValueError:
            have_3pts = False
            F_skull = None

    if not have_3pts and have_2pts:
        src = lm.lambda_brain - lm.bregma_brain
        src = src / np.linalg.norm(src)
        dst = lm.lambda_skull - lm.bregma_skull
        dst = dst / np.linalg.norm(dst)
        cross = np.cross(src, dst)
        dot = float(np.dot(src, dst))
        if np.linalg.norm(cross) < 1e-6:
            R4 = np.eye(4) if dot > 0 else trimesh.transformations.rotation_matrix(np.pi, [0, 1, 0])
        else:
            axis = cross / np.linalg.norm(cross)
            R4 = trimesh.transformations.rotation_matrix(
                np.arctan2(np.linalg.norm(cross), dot), axis, point=lm.bregma_brain
            )
    elif not have_2pts:
        R4 = np.eye(4)

    bregma_brain = xform_pt(lm.bregma_brain, R4)
    lambda_brain = xform_pt(lm.lambda_brain, R4)
    ventral_brain = xform_pt(lm.ventral_brain, R4)

    if have_3pts and bregma_brain is not None:
        # Work in the skull's own landmark-derived (e1, e2, e3) basis --
        # F_skull's columns -- rather than either mesh's raw STL axes, so
        # "per axis" means per anatomical direction regardless of how
        # either file happens to be oriented. R4 already rotates the
        # brain's landmarks into this same basis (expressed in the
        # skull's raw coordinates), so a plain F_skull.T projection
        # applies to both meshes' (already-rotated) landmark vectors.
        bl_skull = F_skull.T @ (lm.lambda_skull - lm.bregma_skull)
        bl_brain = F_skull.T @ (lambda_brain - bregma_brain)
        bv_skull = F_skull.T @ (lm.ventral_skull - lm.bregma_skull)
        bv_brain = F_skull.T @ (ventral_brain - bregma_brain)
        skull_ref = np.abs(bl_skull) + np.abs(bv_skull)
        brain_ref = np.abs(bl_brain) + np.abs(bv_brain)

        # Extent ratio along each local direction, for the fallback (and
        # for medio-lateral, which always uses it). The brain mesh is
        # still in its own raw frame, so its bbox-extent direction is the
        # skull-frame direction rotated back by R4's inverse (transpose).
        R3_inv = R4[:3, :3].T
        skull_extent = np.array([extent_along(skull, F_skull[:, i]) for i in range(3)])
        brain_extent = np.array([extent_along(brain, R3_inv @ F_skull[:, i]) for i in range(3)])
        bbox_ratio = skull_extent / brain_extent
        with np.errstate(divide="ignore", invalid="ignore"):
            scales = np.where(brain_ref > 1e-3, skull_ref / brain_ref, bbox_ratio)
    else:
        bbox_ratio = bbox_dims(skull) / bbox_dims(brain)
        scales = bbox_ratio

    # The medio-lateral axis is always driven by `cavity_scale`, never by
    # the landmarks (see MEDIOLATERAL_AXIS) -- e.g. cavity_scale=0.9 makes
    # the brain 90% as wide as the skull's own medio-lateral extent. The
    # antero-posterior and dorso-ventral axes keep the exact
    # landmark-distance ratio above, unaffected by `cavity_scale`.
    scales = scales.copy()
    scales[MEDIOLATERAL_AXIS] = bbox_ratio[MEDIOLATERAL_AXIS] * cavity_scale

    pivot = bregma_brain if bregma_brain is not None else bbox_center(brain)
    T_to_o = np.eye(4)
    T_to_o[:3, 3] = -pivot
    T_from_o = np.eye(4)
    T_from_o[:3, 3] = pivot

    if F_skull is not None:
        # Anisotropic scale along the (possibly non-axis-aligned) e1/e2/e3
        # directions: sandwich the diagonal scale between the local basis
        # and its inverse (F_skull is orthonormal, so F_skull.T = inverse).
        S3 = F_skull @ np.diag(scales) @ F_skull.T
    else:
        S3 = np.diag(scales)
    S4 = np.eye(4)
    S4[:3, :3] = S3
    scale_M = T_from_o @ S4 @ T_to_o

    br_post = xform_pt(bregma_brain, scale_M)

    if br_post is not None and lm.bregma_skull is not None:
        translation = lm.bregma_skull - br_post
    else:
        translation = bbox_center(skull) - bbox_center(brain)

    T = np.eye(4)
    T[:3, 3] = translation
    full_4x4 = T @ scale_M @ R4

    # Re-express everything in a canonical, skull-anchored frame: skull
    # Bregma at the origin, skull Lambda on +X (antero-posterior) at the
    # Bregma-Lambda distance. This is a rigid (no-scale) transform derived
    # purely from the skull's own 3 landmarks, composed on top of the
    # brain's skull-relative alignment above.
    if lm.bregma_skull is not None and lm.lambda_skull is not None and lm.ventral_skull is not None:
        skull_canonical = canonical_frame_transform(lm.bregma_skull, lm.lambda_skull, lm.ventral_skull)
    else:
        skull_canonical = np.eye(4)
    full_4x4 = skull_canonical @ full_4x4

    return {
        "skull_stl": str(skull_path),
        "brain_stl": str(brain_path),
        "full_4x4": full_4x4.tolist(),
        "skull_canonical_4x4": skull_canonical.tolist(),
        "scale_xyz": scales.tolist(),
        "translation_xyz": translation.tolist(),
        "cavity_scale": cavity_scale,
        "landmarks": lm.as_json(),
    }


def apply_transform(transform: dict, mesh_path: str, output_path: str) -> trimesh.Trimesh:
    """Apply a transform dict to a single STL and save the result."""
    mesh = trimesh.load(str(mesh_path))
    mesh.apply_transform(np.array(transform["full_4x4"]))
    mesh.export(str(output_path))
    return mesh
